[package]
name = "weirs"
version = "0.1.0"
edition = "2024"
description = "A minimalist VPN client"
keywords = ["vpn", "fortinet"]
categories = ["network-programming", "command-line-utilities"]
repository = "https://github.com/sauromates/weirs"
license = "Apache-2.0"

[dependencies]
async-trait = "0.1.89"
clap = { version = "4.6.0", features = ["derive"] }
futures = "0.3.32"
reqwest = { version = "0.13.2", features = ["cookies", "form"] }
rpassword = "7.4.0"
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.50.0", features = ["full"] }
toml = "1.0.6"
url = "2.5.8"

[dev-dependencies]
wiremock = "0.6.5"
